version: '3.7'

services:
  notification.api:
    container_name: "notification_api"
    image: "elwark/notification/api:${TAG:-latest}"
    build:
      context: .
      dockerfile: src/Notification.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Kestrel__EndPoints__Grpc__Url=http://+:80
