version: '3.7'

services:
  notification:
    container_name: "notification"
    image: elwark/notification:${TAG:-latest}
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:80"